# Generated by Django 4.2.2 on 2023-06-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreClub', models.CharField(max_length=50)),
                ('nombreEstadio', models.CharField(max_length=50)),
                ('direccionEstadio', models.CharField(max_length=50)),
                ('capacidadEstadio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipoLocal', models.CharField(max_length=50)),
                ('equipoVisitante', models.CharField(max_length=50)),
                ('fechaPartido', models.DateField()),
                ('horarioPartido', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
